version: '3.8'

services:
  api:
    container_name: codechat_api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8084:8084
    volumes:
      - instances_connecteds:/codechat/instances
    environment:
      - SERVER_PORT=8084
      - SESSION_SECRET=W0NvZGVDaGF0XTpbU2Vzc

      - LOG_LEVEL=ERROR|WARN|INFO|DEBUG|LOG|VERBOSE|DARK
      - LOG_COLOR=true

      - DATABASE_ENABLED=true
      - DATABASE_URL=postgresql://postgres:xdc77ukoki8ju@postgres_whatsapp:5432/whatsapp?schema=public
      - DATABASE_SYNC_MESSAGES=true
      - DATABASE_SAVE_DATA_NEW_MESSAGE=true
      - DATABASE_SAVE_MESSAGE_UPDATE=true
      - DATABASE_SAVE_DATA_CONTACTS=true
      - DATABASE_SAVE_DATA_CHATS=true

      - GLOBAL_WEBHOOK_URL=url
      - GLOBAL_WEBHOOK_ENABLED=false

      - INSTANCE_EXPIRATION_TIME=false

      - CONFIG_SESSION_PHONE_CLIENT=CodeChat_V1
      - CONFIG_SESSION_PHONE_NAME=Edge

      - WA_VERSION=[ 2, 3000, 1015901307 ]

      - QRCODE_LIMIT=10
      - QRCODE_EXPIRATION_TIME=60
      - QRCODE_LIGHT_COLOR=#ffffff
      - QRCODE_DARK_COLOR=#198754

      - CONNECTION_TIMEOUT=300

      - AUTHENTICATION_GLOBAL_AUTH_TOKEN=zYzP7ocstxh3SJ23D4FZTCu4ehnM8v4hu
      - AUTHENTICATION_JWT_EXPIRES_IN=0
      - AUTHENTICATION_JWT_SECRET=3RFYiiRmvNiokSBrLZzx

      - PROVIDER_ENABLED=false
      - PROVIDER_HOST=127.0.0.1
      - PROVIDER_PORT=5656
      - PROVIDER_PREFIX=codechat

      - BASE_URL=

    networks:
      - public-network
    depends_on:
      - postgres_whatsapp

  postgres_whatsapp:
    container_name: postgres_whatsapp
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: xdc77ukoki8ju
      POSTGRES_DB: whatsapp
    ports:
      - '5439:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - public-network

networks:
  public-network:
    driver: bridge

volumes:
  instances_connecteds:
    name: instances_connecteds
    external: true
  postgres_data:
    name: postgres_data
